# Exported from Render on 2024-12-03T05:13:17Z
services:
- type: web
  name: DjangoApp
  runtime: python
  repo: https://github.com/dfluechter/Projekt
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: PYTHON_VERSION
    sync: false
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn mywebsite.wsgi:application
version: "1"
